
OrdererOrgs:
  - Name: Energy 
    Domain: energy.com
    CA:
        Country: Spain
        Province: Alicante
        Locality: Alicante
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: RenewableEnergy
    Domain: renewable.energy.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: NonRenewable
    Domain: nonrenewable.energy.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: ElectricNetwork
    Domain: electricnetwork.energy.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Distributor1
    Domain: distributor1.energy.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Distributor2
    Domain: distributor2.energy.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Regulator
    Domain: regulator.energy.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2
