version: "3.3"
services:
  app:
    build: ./
    container_name: front-app
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
